#spring.cloud.stream.bindings.input.group = test
#spring.cloud.stream.bindings.input.destination = input

#spring.cloud.stream.bindings.output.group = test
#spring.cloud.stream.bindings.output.destination = output



spring:
  cloud:
    stream:
      bindings:
        input:
          destination: input
          binder: local_rabbit
          group: test
        output:
          destination: output
          binder: local_kafka
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
        local_kafka:
          type: kafka
          enviornment:
            spring:
              kafka:
                consumer:
                  bootstrap-servers: localhost:9092
                  group-id: group_id
                  auto-offset-reset: earliest
                  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                producer:
                  bootstrap-servers: localhost:9092
                  key-serializer: org.apache.kafka.common.serialization.StringSerializer
                  value-serializer: org.apache.kafka.common.serialization.StringSerializer